name: Development Builds

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  VULTR_REGISTRY: sjc.vultrcr.com
  VULTR_IMAGE_NAME: seven/lucky-tgbot
  GHCR_IMAGE_NAME: realsunyz/lucky-tgbot

jobs:
  docker-dev:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login in to Vultr Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.VULTR_REGISTRY }}
          username: ${{ secrets.VULTR_USERNAME }}
          password: ${{ secrets.VULTR_PASSWORD }}

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        id: image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}:dev
            ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}:dev-${{ github.sha }}
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:dev
            ghcr.io/${{ env.GHCR_IMAGE_NAME }}:dev-${{ github.sha }}
          cache-from: type=gha,scope=dev-amd64
          cache-to: type=gha,mode=max,scope=dev-amd64

      - name: Generate Artifact Attestation (GHCR)
        if: github.event_name != 'pull_request'
        uses: actions/attest-build-provenance@v3
        continue-on-error: true
        with:
          subject-name: ghcr.io/${{ env.GHCR_IMAGE_NAME }}
          subject-digest: ${{ steps.image.outputs.digest }}
          push-to-registry: true

      - name: Generate Artifact Attestation (Vultr)
        if: github.event_name != 'pull_request'
        uses: actions/attest-build-provenance@v3
        continue-on-error: true
        with:
          subject-name: ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}
          subject-digest: ${{ steps.image.outputs.digest }}
          push-to-registry: true
